// Code generated by tools/genbaseline; DO NOT EDIT.
// Source: shared/consistency/baseline/ (run `go run ./tools/genbaseline` to regenerate).

package sim

const (
	BaselineRelationAnnualDecayK                  = 0.05
	BaselineMinutesPerDay                         = 1440
	BaselineAddictionCravingDecayPerDay           = 0.5
	BaselineAddictionDependentMin                 = 20.0
	BaselineAddictionSevereMin                    = 60.0
	BaselineAddictionWithdrawalTriggerHours       = 12.0
	BaselineAestheticsIllegalComplicationMult     = 2.2
	BaselineAestheticsIllegalSuccessMult          = 0.55
	BaselineAestheticsMalpracticeCompensation     = 3000000
	BaselineAestheticsOverMedicalizationThreshold = 5
	BaselineAestheticsStiffnessPerProcedure       = 8.0
	BaselineBankCreditMax                         = 1000
	BaselineBankCreditMin                         = 0
	BaselineBankCreditOverduePenalty              = 100
	BaselineBankCreditStart                       = 700
	BaselineBankDefaultOverdueDays                = 0
	BaselineBankDemandRateAnnual                  = 0.003
	BaselineBankFixedRateAnnual                   = 0.02
	BaselineBankLoanRateAnnual                    = 0.05
	BaselineBankOverdueDaysDowngrade              = 30
	BaselineCleanlinessDecayPerMin                = 0.06944444444444445
	BaselineCpReturnWindowDays                    = 7
	BaselineCpThreeGuaranteeDays                  = 15
	BaselineCpWarrantyDefectDays                  = 180
	BaselineCurrencyBase                          = "USD"
	BaselineDehydrateHealthPerHour                = 4.0
	BaselineDigitalAddictionThresholdHours        = 8.0
	BaselineDsBankruptcyEraStart                  = 2021
	BaselineDsInterestRateCap                     = 0.36
	BaselineDsP2pEraEnd                           = 2020
	BaselineDsP2pEraStart                         = 2013
	BaselineDyingHealthMargin                     = 30.0
	BaselineDyingHealthThreshold                  = 10.0
	BaselineDyingLifespanMarginYears              = 2.0
	BaselineEarthRadiusKm                         = 6371.0
	BaselineEmploymentBaseHireDifficulty          = 0.7
	BaselineEmploymentUnemploymentSensitivity     = 3.0
	BaselineEmploymentWageUnemploymentSensitivity = 1.5
	BaselineEmCommandFaultLine                    = 0.5
	BaselineEmDefaultResponseCap                  = 60.0
	BaselineEmSecondaryBaseRisk                   = 0.15
	BaselineEmSurvivalTreated                     = 0.9
	BaselineEmSurvivalUntreated                   = 0.35
	BaselineEngineeringAcceptanceQualityThreshold = 0.6
	BaselineEnvCarbonFineMultiplier               = 3.0
	BaselineEnvDefaultCarbonPrice                 = 100
	BaselineEnvEsgEmissionPenalty                 = 0.5
	BaselineEnvEsgFineDivisor                     = 100000.0
	BaselineEnvEsgFraudPenalty                    = 30.0
	BaselineEnvEsgGradeA                          = 80.0
	BaselineEnvEsgGradeB                          = 65.0
	BaselineEnvEsgGradeC                          = 50.0
	BaselineEnvEsgGreenInvestmentCap              = 15.0
	BaselineEnvEsgGreenInvestmentUnit             = 1e+06
	BaselineEnvEsgIllegalPenalty                  = 20.0
	BaselineEnvEsgScoreMax                        = 100.0
	BaselineEnvFootprintScope1                    = 0.5
	BaselineEnvFootprintScope2                    = 0.3
	BaselineEnvFootprintScope3                    = 0.2
	BaselineEraCount                              = 9
	BaselineFxAnnualVolatility                    = 0.08
	BaselineFxFeeRate                             = 0.001
	BaselineFxMeanReversion                       = 0.15
	BaselineFxSpreadBps                           = 50.0
	BaselineGbmCryptoVolatility                   = 0.8
	BaselineGbmDriftDefault                       = 0.08
	BaselineGbmDriftMax                           = 0.15
	BaselineGbmDriftMin                           = 0.05
	BaselineGbmPriceFloor                         = 1e-06
	BaselineGbmVolatilityDefault                  = 0.3
	BaselineGbmVolatilityMax                      = 0.5
	BaselineGbmVolatilityMin                      = 0.2
	BaselineGeoMinTotalLocations                  = 1000
	BaselineHealthRegenAgeDecayPerYear            = 0.01
	BaselineHealthRegenPerHour                    = 1.0
	BaselineHungerDecayPerMin                     = 0.21
	BaselineIndividualTradeInfluence              = 1e-06
	BaselineInsurancePayoutRate                   = 1.0
	BaselineInsurancePremiumRate                  = 0.02
	BaselineLifespanBaseYears                     = 78.0
	BaselineLotteryPayoutMinor                    = 10000
	BaselineLotteryTicketPriceMinor               = 200
	BaselineLotteryWinChance                      = 0.001
	BaselineMacroBaseInflation                    = 0.02
	BaselineMacroBaseRate                         = 0.03
	BaselineMacroCycleMaxQuarters                 = 16
	BaselineMacroCycleMinQuarters                 = 4
	BaselineMacroGdpGrowthBase                    = 0.03
	BaselineMacroInflationMax                     = 3.0
	BaselineMacroInflationMin                     = -0.05
	BaselineMacroInflationUnemploymentTradeoff    = 0.4
	BaselineMacroPmiBase                          = 50.0
	BaselineMacroPmiMax                           = 100.0
	BaselineMacroPmiMin                           = 0.0
	BaselineMacroQuartersPerYear                  = 4
	BaselineMacroRateMax                          = 0.5
	BaselineMacroRateMin                          = 0.0
	BaselineMacroRateUnemploymentSensitivity      = 0.8
	BaselineMacroUnemploymentBase                 = 0.05
	BaselineMacroUnemploymentMax                  = 1.0
	BaselineMacroUnemploymentMin                  = 0.0
	BaselineMacroWageLagQuarters                  = 1
	BaselineMarginInitialRatio                    = 0.5
	BaselineMarginLiquidationFee                  = 0.01
	BaselineMarginMaintenanceRatio                = 0.25
	BaselineMedicalMisdiagnosisChance             = 0.1
	BaselineMedicalUntreatedFreeDays              = 7.0
	BaselineMedicalUntreatedHealthDecayPerDay     = 1.0
	BaselineMhStressDisorderThreshold             = 70.0
	BaselineMoneyMinorScale                       = 100
	BaselineMoodRecoverPerHour                    = 1.0
	BaselineNutritionAgeBaseYears                 = 20.0
	BaselineNutritionAgeScalePerYear              = 0.01
	BaselineNutritionExcessDaysRequired           = 30.0
	BaselineNutritionExcessThreshold              = 85.0
	BaselineNutritionLaborScale                   = 0.3
	BaselineNutritionLightThreshold               = 30.0
	BaselineNutritionSevereThreshold              = 15.0
	BaselineOrgTradeInfluence                     = 0.001
	BaselinePriceCeilRatio                        = 5.0
	BaselinePriceDemandToPrice                    = 0.5
	BaselinePriceFloorRatio                       = 0.2
	BaselineRegionBirthRateAnnual                 = 0.012
	BaselineRegionDaysPerYear                     = 365.25
	BaselineRegionDeathRateAnnual                 = 0.009
	BaselineRegionEconomyGrowthAnnual             = 0.02
	BaselineRegionEventRateAnnual                 = 1.0
	BaselineRegionInflationRateAnnual             = 0.02
	BaselineRegionMigrationRateAnnual             = 0.0
	BaselineSeirAlertAlertOccupancy               = 1.0
	BaselineSeirAlertAlertPrevalence              = 0.005
	BaselineSeirAlertEmergencyOccupancy           = 1.5
	BaselineSeirAlertEmergencyPrevalence          = 0.02
	BaselineSeirAlertWatchPrevalence              = 0.0005
	BaselineSeirBedsDivisor                       = 1000.0
	BaselineSeirBetaReductionCap                  = 0.95
	BaselineSeirDefaultVaccineHesitancy           = 0.2
	BaselineSeirDoctorsDivisor                    = 500.0
	BaselineSeirImmunityWaneRate                  = 0.1
	BaselineSeirPolicyTrustPenalty                = 0.02
	BaselineSeirStageDecliningRatio               = 0.01
	BaselineSeirStagePeakRatio                    = 0.98
	BaselineSeirStageResolvedInfectious           = 0.5
	BaselineSeirSurgeExtraSlope                   = 0.5
	BaselineSeirTestKitsDivisor                   = 100.0
	BaselineSeirVaccineAcceptanceNoise            = 0.1
	BaselineSeirVaccineStockDivisor               = 250.0
	BaselineSeirVentilatorsDivisor                = 20000.0
	BaselineSleepDebtGainPerHour                  = 4.166666666666667
	BaselineSleepDebtIntelligencePenaltyPerHour   = 2.0
	BaselineSleepDebtMoodPenaltyPerHour           = 3.0
	BaselineSleepDebtRecoverPerHour               = 12.5
	BaselineSleepDebtThreshold                    = 60.0
	BaselineSportsAgeDeclineRate                  = 0.97
	BaselineSportsAgeFloor                        = 0.3
	BaselineSportsDopingBanChance                 = 0.3
	BaselineSportsDopingBoost                     = 10.0
	BaselineSportsInjuryBaseRisk                  = 0.02
	BaselineSportsInjuryPenalty                   = 8.0
	BaselineSportsPeakMaxAge                      = 28
	BaselineSportsPeakMinAge                      = 22
	BaselineSportsTrainRate                       = 0.4
	BaselineStaminaDrainPerHour                   = 20.0
	BaselineStaminaRegenAsleepPerHour             = 12.5
	BaselineStaminaRegenAwakePerHour              = 5.0
	BaselineStarveHealthPerHour                   = 2.0
	BaselineTaxConsumptionRate                    = 0.1
	BaselineTaxCorporateRate                      = 0.25
	BaselineTaxEvasionAuditChance                 = 0.15
	BaselineTaxPropertyRateAnnual                 = 0.012
	BaselineTaxSocialSecurityRate                 = 0.08
	BaselineTaxStampRate                          = 0.001
	BaselineTaxStandardDeduction                  = 6000.0
	BaselineTaxVatRate                            = 0.13
	BaselineThirstDecayPerMin                     = 0.42
	BaselineTransportCongestionPeakFactor         = 1.5
	BaselineTransportTransferMinutesDefault       = 8.0
	BaselineWeatherDaysPerYear                    = 365.25
	BaselineWeatherDerivedNoiseSigma              = 1.5
	BaselineWeatherDisasterWarningMaxDays         = 3
	BaselineWeatherDisasterWarningMinDays         = 1
	BaselineWeatherForecastAccuracyDecay          = 0.82
	BaselineWeatherForecastAccuracyMin            = 0.05
	BaselineWeatherForecastDays                   = 7
	BaselineWeatherHumidityMax                    = 100.0
	BaselineWeatherHumidityMin                    = 0.0
	BaselineWeatherMarkovFamilyContinuity         = 1.3
	BaselineWeatherMarkovPersistence              = 2.5
	BaselineWeatherMaxHistoryDays                 = 4096
	BaselineWeatherMinStateWeight                 = 0.001
	BaselineWeatherPrecipMax                      = 200.0
	BaselineWeatherPrecipMin                      = 0.0
	BaselineWeatherPressureMax                    = 1050.0
	BaselineWeatherPressureMin                    = 950.0
	BaselineWeatherSnowTempThreshold              = 2.0
	BaselineWeatherTempMax                        = 60.0
	BaselineWeatherTempMin                        = -60.0
	BaselineWeatherTempNoiseSigma                 = 2.0
	BaselineWeatherVisibilityMax                  = 50.0
	BaselineWeatherVisibilityMin                  = 0.0
	BaselineWeatherWindMax                        = 60.0
	BaselineWeatherWindMin                        = 0.0
)

var (
	BaselineRanges map[string][2]int = map[string][2]int{
		"attribute":   {0, 100},
		"awe":         {0, 100},
		"favor":       {-100, 100},
		"grudge":      {-100, 100},
		"intimacy":    {0, 100},
		"personality": {0, 100},
		"skill":       {0, 20},
		"trust":       {0, 100},
		"values_axis": {0, 100},
	}
	BaselineSpeedLevels      []any          = []any{0, 1, 2, 4, 60, 3600, 86400}
	BaselineDayPhases        map[string]any = map[string]any{"dawn_start_hour": 5, "day_start_hour": 8, "dusk_start_hour": 18, "night_start_hour": 21}
	BaselineAddictionSpecies map[string]any = map[string]any{
		"alcohol":  map[string]any{"dose_gain": 4.0, "physiological": true, "relapse_rate": 0.45, "tolerance_growth": 0.03, "treatment_days": 30.0, "withdrawal_days": 10.0, "withdrawal_intensity": 8.0},
		"drug":     map[string]any{"dose_gain": 6.0, "physiological": true, "relapse_rate": 0.6, "tolerance_growth": 0.05, "treatment_days": 60.0, "withdrawal_days": 14.0, "withdrawal_intensity": 12.0},
		"gambling": map[string]any{"dose_gain": 2.5, "physiological": false, "relapse_rate": 0.5, "tolerance_growth": 0.02, "treatment_days": 45.0, "withdrawal_days": 14.0, "withdrawal_intensity": 5.0},
		"internet": map[string]any{"dose_gain": 2.0, "physiological": false, "relapse_rate": 0.35, "tolerance_growth": 0.02, "treatment_days": 30.0, "withdrawal_days": 14.0, "withdrawal_intensity": 4.0},
		"tobacco":  map[string]any{"dose_gain": 3.0, "physiological": true, "relapse_rate": 0.4, "tolerance_growth": 0.02, "treatment_days": 30.0, "withdrawal_days": 7.0, "withdrawal_intensity": 6.0},
	}
	BaselineAddictionTreatment map[string]any = map[string]any{
		"counseling":   map[string]any{"reduction": 0.2, "success_bonus": 0.15},
		"inpatient":    map[string]any{"reduction": 0.5, "success_bonus": 0.4},
		"substitution": map[string]any{"reduction": 0.3, "success_bonus": 0.25},
	}
	BaselineClimateZones map[string]any = map[string]any{
		"mediterranean":         map[string]any{"amp_diurnal": 9.0, "amp_temp": 9.0, "arid": 0.5, "base_temp": 17.0, "can_snow": false, "humidity": 55.0, "monsoon": false, "name": "地中海", "phase": 0.0, "precip_scale": 3.0, "pressure": 1013.0, "visibility": 18.0, "wind": 3.5},
		"polar_highland":        map[string]any{"amp_diurnal": 8.0, "amp_temp": 15.0, "arid": 0.6, "base_temp": -20.0, "can_snow": true, "humidity": 45.0, "monsoon": false, "name": "极地高原", "phase": 0.0, "precip_scale": 0.8, "pressure": 1008.0, "visibility": 10.0, "wind": 6.0},
		"subarctic_conifer":     map[string]any{"amp_diurnal": 9.0, "amp_temp": 18.0, "arid": 0.2, "base_temp": -4.0, "can_snow": true, "humidity": 65.0, "monsoon": false, "name": "亚寒带针叶林", "phase": 0.0, "precip_scale": 1.5, "pressure": 1012.0, "visibility": 12.0, "wind": 3.0},
		"subtropical_monsoon":   map[string]any{"amp_diurnal": 9.0, "amp_temp": 12.0, "arid": 0.1, "base_temp": 17.0, "can_snow": true, "humidity": 70.0, "monsoon": true, "name": "亚热带季风", "phase": -0.5, "precip_scale": 5.0, "pressure": 1010.0, "visibility": 12.0, "wind": 3.0},
		"temperate_continental": map[string]any{"amp_diurnal": 11.0, "amp_temp": 16.0, "arid": 0.3, "base_temp": 8.0, "can_snow": true, "humidity": 55.0, "monsoon": false, "name": "温带大陆", "phase": 0.0, "precip_scale": 2.0, "pressure": 1014.0, "visibility": 15.0, "wind": 3.5},
		"temperate_oceanic":     map[string]any{"amp_diurnal": 6.0, "amp_temp": 7.0, "arid": 0.05, "base_temp": 11.0, "can_snow": true, "humidity": 78.0, "monsoon": false, "name": "温带海洋", "phase": 0.2, "precip_scale": 3.5, "pressure": 1012.0, "visibility": 12.0, "wind": 4.5},
		"tropical_desert":       map[string]any{"amp_diurnal": 18.0, "amp_temp": 12.0, "arid": 0.95, "base_temp": 30.0, "can_snow": false, "humidity": 20.0, "monsoon": false, "name": "热带沙漠", "phase": 0.0, "precip_scale": 0.3, "pressure": 1005.0, "visibility": 25.0, "wind": 4.0},
		"tropical_monsoon":      map[string]any{"amp_diurnal": 8.0, "amp_temp": 6.0, "arid": 0.1, "base_temp": 26.0, "can_snow": false, "humidity": 75.0, "monsoon": true, "name": "热带季风", "phase": -1.0, "precip_scale": 8.0, "pressure": 1008.0, "visibility": 15.0, "wind": 3.0},
		"tropical_rainforest":   map[string]any{"amp_diurnal": 6.0, "amp_temp": 2.0, "arid": 0.0, "base_temp": 26.0, "can_snow": false, "humidity": 85.0, "monsoon": true, "name": "热带雨林", "phase": 0.0, "precip_scale": 12.0, "pressure": 1008.0, "visibility": 15.0, "wind": 2.0},
		"tropical_savanna":      map[string]any{"amp_diurnal": 12.0, "amp_temp": 5.0, "arid": 0.4, "base_temp": 27.0, "can_snow": false, "humidity": 55.0, "monsoon": false, "name": "热带草原", "phase": 0.5, "precip_scale": 4.0, "pressure": 1010.0, "visibility": 20.0, "wind": 3.0},
	}
	BaselineClimateZoneOrder []any          = []any{"tropical_rainforest", "tropical_monsoon", "tropical_savanna", "tropical_desert", "subtropical_monsoon", "mediterranean", "temperate_oceanic", "temperate_continental", "subarctic_conifer", "polar_highland"}
	BaselineCpChannelWeights map[string]any = map[string]any{"class_action": 0.9, "consumer_association": 0.7, "hotline_12315": 0.6, "litigation": 0.85, "negotiate": 0.25, "platform": 0.4}
	BaselineCurrencies       map[string]any = map[string]any{
		"CNY": map[string]any{"name": "人民币", "rate": 7.0},
		"EUR": map[string]any{"name": "欧元", "rate": 0.92},
		"GBP": map[string]any{"name": "英镑", "rate": 0.8},
		"JPY": map[string]any{"name": "日元", "rate": 150.0},
		"KRW": map[string]any{"name": "韩元", "rate": 1350.0},
		"USD": map[string]any{"name": "美元", "rate": 1.0},
	}
	BaselineDeCareModes map[string]any = map[string]any{
		"community_care":   map[string]any{"cost_per_month": 600000, "happiness": 2.0, "life_modifier": 0.1, "name": "社区养老", "quality": 0.65},
		"home_care":        map[string]any{"cost_per_month": 400000, "happiness": 0.0, "life_modifier": 0.0, "name": "居家护理", "quality": 0.5},
		"institution_care": map[string]any{"cost_per_month": 1200000, "happiness": -1.0, "life_modifier": 0.2, "name": "机构养老", "quality": 0.8},
	}
	BaselineDeDevices map[string]any = map[string]any{
		"accessibility": map[string]any{
			"cost":           500000,
			"mobility_bonus": 0.2,
			"name":           "无障碍改造",
			"types":          []any{"physical", "sensory"},
		},
		"guide_dog": map[string]any{
			"cost":           300000,
			"mobility_bonus": 0.35,
			"name":           "导盲犬",
			"types":          []any{"sensory"},
		},
		"hearing_aid": map[string]any{
			"cost":           200000,
			"mobility_bonus": 0.1,
			"name":           "助听器",
			"types":          []any{"sensory"},
		},
		"prosthesis": map[string]any{
			"cost":           1500000,
			"mobility_bonus": 0.4,
			"name":           "义肢",
			"types":          []any{"physical"},
		},
		"rehab": map[string]any{
			"cost":           100000,
			"mobility_bonus": 0.15,
			"name":           "康复训练",
			"types":          []any{"physical", "sensory", "intellectual", "mental"},
		},
		"wheelchair": map[string]any{
			"cost":           800000,
			"mobility_bonus": 0.5,
			"name":           "轮椅",
			"types":          []any{"physical"},
		},
	}
	BaselineDeSeverityPenalty       map[string]any = map[string]any{"heavy": 0.75, "light": 0.15, "medium": 0.4}
	BaselineDigitalContentPlatforms map[string]any = map[string]any{
		"livestream":  map[string]any{"base_views": 20000, "conversion": 0.05, "cut": 0.3, "name": "直播", "tip_rate": 0.02},
		"short_video": map[string]any{"base_views": 60000, "conversion": 0.08, "cut": 0.2, "name": "短视频", "tip_rate": 0.005},
	}
	BaselineDigitalHackTargets map[string]any = map[string]any{
		"black_market": map[string]any{"base_gain": 800000, "difficulty": 12.0, "exposure": 0.5, "fine": 300000, "name": "黑产", "sentence_days": 365, "wanted": 1},
		"enterprise":   map[string]any{"base_gain": 500000, "difficulty": 10.0, "exposure": 0.4, "fine": 500000, "name": "企业", "sentence_days": 730, "wanted": 2},
		"government":   map[string]any{"base_gain": 2000000, "difficulty": 15.0, "exposure": 0.6, "fine": 2000000, "name": "政府", "sentence_days": 1825, "wanted": 3},
		"personal":     map[string]any{"base_gain": 20000, "difficulty": 6.0, "exposure": 0.25, "fine": 50000, "name": "个人", "sentence_days": 180, "wanted": 1},
	}
	BaselineDigitalSecurityJobs map[string]any = map[string]any{
		"breach_disposal":   map[string]any{"difficulty": 10.0, "income": 200000, "name": "数据泄露处置", "reputation": 1.5},
		"defense":           map[string]any{"difficulty": 7.0, "income": 90000, "name": "安全防护", "reputation": 0.8},
		"incident_response": map[string]any{"difficulty": 9.0, "income": 150000, "name": "应急响应", "reputation": 1.2},
		"pentest":           map[string]any{"difficulty": 8.0, "income": 120000, "name": "渗透测试", "reputation": 1.0},
	}
	BaselineDsBusinesses map[string]any = map[string]any{
		"consumer_finance": map[string]any{"collateral_required": false, "era": "all", "name": "消费金融", "rate_cap": 0.24, "requires_license": true},
		"crowdfunding":     map[string]any{"collateral_required": false, "era": "all", "name": "众筹", "rate_cap": 0.0, "requires_license": true},
		"micro_loan":       map[string]any{"collateral_required": false, "era": "all", "name": "小额信贷", "rate_cap": 0.24, "requires_license": true},
		"p2p":              map[string]any{"collateral_required": false, "era": "2013-2020", "name": "P2P", "rate_cap": 0.24, "requires_license": true},
		"pawn":             map[string]any{"collateral_required": true, "era": "all", "name": "典当", "rate_cap": 0.36, "requires_license": true},
		"private_lending":  map[string]any{"collateral_required": false, "era": "all", "name": "民间借贷", "rate_cap": 0.36, "requires_license": false},
	}
	BaselineDsCollectionModes map[string]any = map[string]any{
		"harassment": map[string]any{"legal": false, "name": "骚扰", "severity": 0.4},
		"home_visit": map[string]any{"legal": false, "name": "上门施压", "severity": 0.65},
		"litigation": map[string]any{"legal": true, "name": "起诉", "severity": 0.2},
		"reminder":   map[string]any{"legal": true, "name": "短信电话提醒", "severity": 0.1},
		"violence":   map[string]any{"legal": false, "name": "暴力催收", "severity": 0.9},
	}
	BaselineEmProfessions map[string]any = map[string]any{
		"coast_guard": map[string]any{
			"base_response": 15.0,
			"equipment":     []any{"patrol_boat", "life_raft", "sonar"},
			"name":          "海警",
		},
		"earthquake_rescue": map[string]any{
			"base_response": 20.0,
			"equipment":     []any{"hydraulic_tool", "search_dog", "rescue_bed"},
			"name":          "地震救援",
		},
		"ems": map[string]any{
			"base_response": 6.0,
			"equipment":     []any{"ambulance", "defibrillator", "stretcher"},
			"name":          "急救",
		},
		"fire": map[string]any{
			"base_response": 8.0,
			"equipment":     []any{"fire_truck", "aerial_ladder", "breathing_apparatus"},
			"name":          "消防",
		},
		"flood_rescue": map[string]any{
			"base_response": 18.0,
			"equipment":     []any{"rubber_boat", "life_jacket", "pump"},
			"name":          "洪水救援",
		},
		"mountain_rescue": map[string]any{
			"base_response": 30.0,
			"equipment":     []any{"rope_kit", "helicopter", "thermal_drone"},
			"name":          "山地救援",
		},
	}
	BaselineEngineeringChain            []any          = []any{"survey", "design", "cost_estimation", "construction", "supervision", "acceptance"}
	BaselineEngineeringProcurementModes map[string]any = map[string]any{
		"government_tender": map[string]any{"name": "政府招投标"},
		"private":           map[string]any{"name": "私人工程"},
	}
	BaselineEngineeringQualifications map[string]any = map[string]any{
		"first":   map[string]any{"bid_bonus": 0.08, "max_scale": 300000000, "min_capital": 10000000, "name": "一级"},
		"second":  map[string]any{"bid_bonus": 0.0, "max_scale": 80000000, "min_capital": 2000000, "name": "二级"},
		"special": map[string]any{"bid_bonus": 0.15, "max_scale": 1000000000, "min_capital": 50000000, "name": "特级"},
	}
	BaselineEngineeringStages map[string]any = map[string]any{
		"acceptance":      map[string]any{"cost_ratio": 0.01, "duration_ratio": 0.03, "name": "验收", "quality_weight": 0.1},
		"construction":    map[string]any{"cost_ratio": 0.7, "duration_ratio": 0.55, "name": "施工", "quality_weight": 0.4},
		"cost_estimation": map[string]any{"cost_ratio": 0.02, "duration_ratio": 0.04, "name": "造价", "quality_weight": 0.05},
		"design":          map[string]any{"cost_ratio": 0.07, "duration_ratio": 0.15, "name": "设计", "quality_weight": 0.2},
		"supervision":     map[string]any{"cost_ratio": 0.03, "duration_ratio": 0.1, "name": "监理", "quality_weight": 0.15},
		"survey":          map[string]any{"cost_ratio": 0.03, "duration_ratio": 0.08, "name": "勘察", "quality_weight": 0.1},
	}
	BaselineEngineeringZoneTypes map[string]any = map[string]any{
		"commercial":  map[string]any{"land_mult": 1.8, "name": "商业区", "population_pull": 0.3, "traffic_demand": 1.0},
		"green":       map[string]any{"land_mult": 0.5, "name": "绿地", "population_pull": 0.2, "traffic_demand": 0.2},
		"industrial":  map[string]any{"land_mult": 0.7, "name": "工业区", "population_pull": 0.4, "traffic_demand": 0.8},
		"mixed":       map[string]any{"land_mult": 1.3, "name": "综合区", "population_pull": 0.8, "traffic_demand": 0.9},
		"residential": map[string]any{"land_mult": 1.0, "name": "居住区", "population_pull": 1.0, "traffic_demand": 0.6},
	}
	BaselineEraDefinitions []any = []any{
		map[string]any{
			"description":       "以采集、狩猎与打制石器为生。",
			"forecast_accuracy": 0.3,
			"key":               "stone",
			"name":              "石器",
			"start_year":        -10000,
			"tags":              []any{"fire", "stone_tools", "tribe"},
		},
		map[string]any{
			"description":       "定居耕作、陶器与早期文字。",
			"forecast_accuracy": 0.4,
			"key":               "agrarian",
			"name":              "农业",
			"start_year":        -3000,
			"tags":              []any{"agriculture", "pottery", "early_writing"},
		},
		map[string]any{
			"description":       "城邦与帝国、哲学与铸币。",
			"forecast_accuracy": 0.46,
			"key":               "classical",
			"name":              "古典",
			"start_year":        -800,
			"tags":              []any{"philosophy", "empire", "coinage"},
		},
		map[string]any{
			"description":       "封建秩序、远洋航行与火药初现。",
			"forecast_accuracy": 0.52,
			"key":               "medieval",
			"name":              "中世纪",
			"start_year":        500,
			"tags":              []any{"feudalism", "compass", "gunpowder_early"},
		},
		map[string]any{
			"description":       "蒸汽、工厂与铁路。",
			"forecast_accuracy": 0.62,
			"key":               "industrial",
			"name":              "工业",
			"start_year":        1700,
			"tags":              []any{"steam", "factory", "railway"},
		},
		map[string]any{
			"description":       "电力、电话与汽车。",
			"forecast_accuracy": 0.7,
			"key":               "electric",
			"name":              "电气",
			"start_year":        1870,
			"tags":              []any{"electricity", "telephone", "automobile"},
		},
		map[string]any{
			"description":       "计算机、互联网与卫星。",
			"forecast_accuracy": 0.85,
			"key":               "information",
			"name":              "信息",
			"start_year":        1970,
			"tags":              []any{"computer", "internet", "satellite"},
		},
		map[string]any{
			"description":       "人工智能、生物科技与新能源。",
			"forecast_accuracy": 0.93,
			"key":               "intelligent",
			"name":              "智能",
			"start_year":        2020,
			"tags":              []any{"ai", "biotech", "renewable"},
		},
		map[string]any{
			"description":       "聚变、星际航行与外星殖民。",
			"forecast_accuracy": 0.98,
			"key":               "interstellar",
			"name":              "星际",
			"start_year":        2100,
			"tags":              []any{"fusion", "spacefaring", "colony"},
		},
	}
	BaselineMacroCycleGdpEffect map[string]any = map[string]any{"boom": 0.05, "recession": -0.04, "recovery": 0.02, "slowdown": 0.01}
	BaselineMacroCyclePhases    []any          = []any{"recession", "recovery", "boom", "slowdown"}
	BaselineMedicalFacilities   map[string]any = map[string]any{
		"clinic": map[string]any{
			"cost_mult":     0.7,
			"medical_level": 0.8,
			"name":          "诊所",
			"reimburse":     0.5,
			"services":      []any{"register", "consult", "medicine"},
		},
		"dental": map[string]any{
			"cost_mult":     1.2,
			"medical_level": 0.9,
			"name":          "牙科",
			"reimburse":     0.4,
			"services":      []any{"register", "consult", "dental", "surgery"},
		},
		"hospital": map[string]any{
			"cost_mult":     1.0,
			"medical_level": 1.0,
			"name":          "综合医院",
			"reimburse":     0.7,
			"services":      []any{"register", "consult", "admit", "surgery", "checkup"},
		},
		"pharmacy": map[string]any{
			"cost_mult":     1.0,
			"medical_level": 0.7,
			"name":          "药店",
			"reimburse":     0.0,
			"services":      []any{"medicine"},
		},
		"psych_clinic": map[string]any{
			"cost_mult":     1.0,
			"medical_level": 0.8,
			"name":          "心理诊所",
			"reimburse":     0.3,
			"services":      []any{"register", "consult", "therapy"},
		},
	}
	BaselineMedicalServiceCost map[string]any = map[string]any{"admit": 200000, "checkup": 50000, "consult": 20000, "dental": 100000, "medicine": 30000, "register": 5000, "surgery": 500000, "therapy": 30000}
	BaselineMhEvents           map[string]any = map[string]any{
		"breakup":      map[string]any{"mood": -15.0, "stress": 16.0},
		"debt":         map[string]any{"mood": -8.0, "stress": 14.0},
		"illness":      map[string]any{"mood": -10.0, "stress": 12.0},
		"marriage":     map[string]any{"mood": 12.0, "stress": 4.0},
		"praise":       map[string]any{"mood": 6.0, "stress": -4.0},
		"promotion":    map[string]any{"mood": 10.0, "stress": 6.0},
		"stay_up":      map[string]any{"mood": -5.0, "stress": 8.0},
		"unemployment": map[string]any{"mood": -12.0, "stress": 18.0},
	}
	BaselineMhTreatments map[string]any = map[string]any{
		"cbt":                 map[string]any{"adherence": 0.7, "cost": 50000, "cure": 0.35, "minutes": 120, "name": "认知行为治疗", "remit": 0.45, "side_effect": 0.03},
		"crisis_intervention": map[string]any{"adherence": 0.85, "cost": 80000, "cure": 0.05, "minutes": 240, "name": "重症干预", "remit": 0.75, "side_effect": 0.08},
		"hospitalization":     map[string]any{"adherence": 0.9, "cost": 300000, "cure": 0.2, "minutes": 14400, "name": "住院治疗", "remit": 0.6, "side_effect": 0.1},
		"medication":          map[string]any{"adherence": 0.65, "cost": 20000, "cure": 0.15, "minutes": 30, "name": "药物治疗", "remit": 0.6, "side_effect": 0.35},
		"psychotherapy":       map[string]any{"adherence": 0.8, "cost": 30000, "cure": 0.25, "minutes": 90, "name": "心理咨询", "remit": 0.5, "side_effect": 0.02},
	}
	BaselineNutritionDecayPerDay    map[string]any = map[string]any{"carbs": 6.0, "fat": 3.0, "minerals": 4.0, "protein": 4.0, "vitamins": 5.0}
	BaselinePriceElasticity         map[string]any = map[string]any{"daily": 0.35, "financial": 1.2, "luxury": 0.9, "necessity": 0.15}
	BaselinePriceSeasonalFactors    map[string]any = map[string]any{"autumn": 1.05, "spring": 1.0, "summer": 1.0, "winter": 1.1}
	BaselineSeirDefaultParams       map[string]any = map[string]any{"beta": 0.5, "gamma": 0.1, "immunity_days": 180.0, "mortality": 0.01, "mutation_rate": 0.001, "sigma": 0.2}
	BaselineSeirPolicyBetaReduction map[string]any = map[string]any{"lockdown": 0.6, "mask": 0.15, "quarantine": 0.3, "school_closure": 0.2, "travel_restriction": 0.25, "vaccine_mandate": 0.1}
	BaselineSeirPolicyEconomyCost   map[string]any = map[string]any{"lockdown": 0.05, "mask": 0.002, "quarantine": 0.02, "school_closure": 0.02, "travel_restriction": 0.03, "vaccine_mandate": 0.004}
	BaselineTaxIncomeBrackets       []any          = []any{
		map[string]any{"rate": 0.03, "upper": 36000.0},
		map[string]any{"rate": 0.1, "upper": 144000.0},
		map[string]any{"rate": 0.2, "upper": 300000.0},
		map[string]any{"rate": 0.25, "upper": 420000.0},
		map[string]any{"rate": 0.3, "upper": 660000.0},
		map[string]any{"rate": 0.35, "upper": 960000.0},
		map[string]any{"rate": 0.45, "upper": -1.0},
	}
	BaselineTaxInheritanceBrackets []any = []any{
		map[string]any{"rate": 0.0, "upper": 500000.0},
		map[string]any{"rate": 0.1, "upper": 1e+06},
		map[string]any{"rate": 0.2, "upper": 3e+06},
		map[string]any{"rate": 0.3, "upper": 1e+07},
		map[string]any{"rate": 0.45, "upper": -1.0},
	}
	BaselineTaxTypes                      []any          = []any{"income", "corporate", "vat", "consumption", "property", "inheritance", "stamp", "social_security"}
	BaselineTransportCongestionCategories []any          = []any{"road", "urban"}
	BaselineTransportModes                map[string]any = map[string]any{
		"airplane": map[string]any{
			"base_fare":       320.0,
			"category":        "air",
			"comfort":         88.0,
			"headway_minutes": 120.0,
			"hub_type":        "airport",
			"name":            "飞机",
			"per_km":          0.55,
			"per_minute":      0.0,
			"requires":        []any{"passport"},
			"speed_kmh":       800.0,
			"wait_minutes":    90.0,
		},
		"bicycle": map[string]any{
			"base_fare":       1.0,
			"category":        "urban",
			"comfort":         50.0,
			"headway_minutes": 0.0,
			"hub_type":        "",
			"name":            "自行车",
			"per_km":          0.0,
			"per_minute":      0.05,
			"requires":        []any{},
			"speed_kmh":       15.0,
			"wait_minutes":    1.0,
		},
		"bus": map[string]any{
			"base_fare":       2.0,
			"category":        "urban",
			"comfort":         55.0,
			"headway_minutes": 12.0,
			"hub_type":        "bus_stop",
			"name":            "公交",
			"per_km":          0.1,
			"per_minute":      0.0,
			"requires":        []any{},
			"speed_kmh":       25.0,
			"wait_minutes":    6.0,
		},
		"coach": map[string]any{
			"base_fare":       4.0,
			"category":        "coach",
			"comfort":         60.0,
			"headway_minutes": 45.0,
			"hub_type":        "coach_station",
			"name":            "长途汽车",
			"per_km":          0.22,
			"per_minute":      0.0,
			"requires":        []any{"id_card"},
			"speed_kmh":       70.0,
			"wait_minutes":    15.0,
		},
		"high_speed_rail": map[string]any{
			"base_fare":       10.0,
			"category":        "rail",
			"comfort":         90.0,
			"headway_minutes": 30.0,
			"hub_type":        "hsr_station",
			"name":            "高铁",
			"per_km":          0.45,
			"per_minute":      0.0,
			"requires":        []any{"id_card"},
			"speed_kmh":       250.0,
			"wait_minutes":    25.0,
		},
		"metro": map[string]any{
			"base_fare":       3.0,
			"category":        "urban",
			"comfort":         70.0,
			"headway_minutes": 6.0,
			"hub_type":        "metro_station",
			"name":            "地铁",
			"per_km":          0.15,
			"per_minute":      0.0,
			"requires":        []any{},
			"speed_kmh":       40.0,
			"wait_minutes":    3.0,
		},
		"ride_hailing": map[string]any{
			"base_fare":       9.0,
			"category":        "road",
			"comfort":         80.0,
			"headway_minutes": 0.0,
			"hub_type":        "",
			"name":            "网约车",
			"per_km":          2.2,
			"per_minute":      0.3,
			"requires":        []any{},
			"speed_kmh":       35.0,
			"wait_minutes":    5.0,
		},
		"self_drive": map[string]any{
			"base_fare":       0.0,
			"category":        "road",
			"comfort":         85.0,
			"headway_minutes": 0.0,
			"hub_type":        "",
			"name":            "自驾",
			"per_km":          0.7,
			"per_minute":      0.0,
			"requires":        []any{"driver_license", "vehicle"},
			"speed_kmh":       50.0,
			"wait_minutes":    0.0,
		},
		"ship": map[string]any{
			"base_fare":       8.0,
			"category":        "water",
			"comfort":         82.0,
			"headway_minutes": 180.0,
			"hub_type":        "port",
			"name":            "轮船",
			"per_km":          0.18,
			"per_minute":      0.0,
			"requires":        []any{},
			"speed_kmh":       40.0,
			"wait_minutes":    30.0,
		},
		"taxi": map[string]any{
			"base_fare":       13.0,
			"category":        "road",
			"comfort":         80.0,
			"headway_minutes": 0.0,
			"hub_type":        "",
			"name":            "出租",
			"per_km":          2.6,
			"per_minute":      0.0,
			"requires":        []any{},
			"speed_kmh":       35.0,
			"wait_minutes":    3.0,
		},
		"train": map[string]any{
			"base_fare":       5.0,
			"category":        "rail",
			"comfort":         75.0,
			"headway_minutes": 60.0,
			"hub_type":        "train_station",
			"name":            "火车",
			"per_km":          0.28,
			"per_minute":      0.0,
			"requires":        []any{"id_card"},
			"speed_kmh":       90.0,
			"wait_minutes":    20.0,
		},
		"walk": map[string]any{
			"base_fare":       0.0,
			"category":        "urban",
			"comfort":         40.0,
			"headway_minutes": 0.0,
			"hub_type":        "",
			"name":            "步行",
			"per_km":          0.0,
			"per_minute":      0.0,
			"requires":        []any{},
			"speed_kmh":       5.0,
			"wait_minutes":    0.0,
		},
	}
	BaselineTransportModeOrder []any          = []any{"walk", "bicycle", "bus", "metro", "taxi", "ride_hailing", "self_drive", "train", "high_speed_rail", "coach", "airplane", "ship"}
	BaselineWeatherDisasters   map[string]any = map[string]any{
		"blizzard": map[string]any{
			"annual_rate":      0.012,
			"name":             "暴雪",
			"seasons":          []any{"winter"},
			"warning_max_days": 3,
			"warning_min_days": 1,
			"zones":            []any{"subarctic_conifer", "polar_highland", "temperate_continental"},
		},
		"drought": map[string]any{
			"annual_rate":      0.02,
			"name":             "干旱",
			"seasons":          []any{"summer"},
			"warning_max_days": 3,
			"warning_min_days": 1,
			"zones":            []any{"tropical_desert", "tropical_savanna", "mediterranean", "subtropical_monsoon"},
		},
		"earthquake": map[string]any{
			"annual_rate":      0.008,
			"name":             "地震",
			"seasons":          []any{},
			"warning_max_days": 1,
			"warning_min_days": 1,
			"zones":            []any{},
		},
		"flood": map[string]any{
			"annual_rate":      0.02,
			"name":             "洪水",
			"seasons":          []any{"summer", "autumn"},
			"warning_max_days": 3,
			"warning_min_days": 1,
			"zones":            []any{"tropical_rainforest", "tropical_monsoon", "subtropical_monsoon", "temperate_oceanic", "tropical_savanna"},
		},
		"hailstorm": map[string]any{
			"annual_rate":      0.008,
			"name":             "冰雹",
			"seasons":          []any{"spring", "summer"},
			"warning_max_days": 2,
			"warning_min_days": 1,
			"zones":            []any{"temperate_continental", "mediterranean", "subtropical_monsoon"},
		},
		"locust": map[string]any{
			"annual_rate":      0.006,
			"name":             "蝗灾",
			"seasons":          []any{"summer", "autumn"},
			"warning_max_days": 3,
			"warning_min_days": 1,
			"zones":            []any{"tropical_savanna", "mediterranean", "subtropical_monsoon"},
		},
		"mudslide": map[string]any{
			"annual_rate":      0.005,
			"name":             "泥石流",
			"seasons":          []any{"summer", "autumn"},
			"warning_max_days": 2,
			"warning_min_days": 1,
			"zones":            []any{"tropical_rainforest", "tropical_monsoon", "subtropical_monsoon"},
		},
		"tsunami": map[string]any{
			"annual_rate":      0.002,
			"name":             "海啸",
			"seasons":          []any{},
			"warning_max_days": 2,
			"warning_min_days": 1,
			"zones":            []any{"tropical_monsoon", "temperate_oceanic", "mediterranean", "subtropical_monsoon"},
		},
		"typhoon": map[string]any{
			"annual_rate":      0.015,
			"name":             "台风",
			"seasons":          []any{"summer", "autumn"},
			"warning_max_days": 3,
			"warning_min_days": 1,
			"zones":            []any{"tropical_monsoon", "tropical_savanna", "subtropical_monsoon", "temperate_oceanic"},
		},
		"wildfire": map[string]any{
			"annual_rate":      0.012,
			"name":             "野火",
			"seasons":          []any{"summer", "autumn"},
			"warning_max_days": 2,
			"warning_min_days": 1,
			"zones":            []any{"tropical_desert", "tropical_savanna", "mediterranean", "temperate_continental"},
		},
	}
	BaselineWeatherDisasterOrder []any          = []any{"earthquake", "flood", "typhoon", "drought", "wildfire", "mudslide", "tsunami", "blizzard", "hailstorm", "locust"}
	BaselineWeatherSeasonKeys    []any          = []any{"spring", "summer", "autumn", "winter"}
	BaselineWeatherStates        map[string]any = map[string]any{
		"clear": map[string]any{
			"affinity":       map[string]any{"cold": 0.1, "dry": 1.2, "hot": 0.3},
			"family":         "clear",
			"humidity_mod":   -20.0,
			"name":           "晴",
			"precip_mm":      0.0,
			"pressure_delta": 8.0,
			"temp_delta":     2.0,
			"visibility_mod": 15.0,
			"wind_mod":       -1.0,
		},
		"cold_wave": map[string]any{
			"affinity":       map[string]any{"cold": 2.0, "dry": 0.8},
			"cold_gate":      true,
			"family":         "cold",
			"humidity_mod":   -6.0,
			"name":           "寒潮",
			"precip_mm":      0.0,
			"pressure_delta": 6.0,
			"temp_delta":     -10.0,
			"visibility_mod": 2.0,
			"wind_mod":       4.0,
		},
		"dust": map[string]any{
			"affinity":       map[string]any{"dry": 1.6, "wind": 0.8},
			"dust":           true,
			"family":         "dust",
			"humidity_mod":   -15.0,
			"name":           "沙尘",
			"precip_mm":      0.0,
			"pressure_delta": -2.0,
			"temp_delta":     0.0,
			"visibility_mod": -30.0,
			"wind_mod":       6.0,
		},
		"fog": map[string]any{
			"affinity":       map[string]any{"cloud": 0.7, "wet": 0.5},
			"family":         "fog",
			"humidity_mod":   30.0,
			"name":           "雾",
			"precip_mm":      0.0,
			"pressure_delta": 1.0,
			"temp_delta":     -1.0,
			"visibility_mod": -35.0,
			"wind_mod":       -2.0,
		},
		"freezing_rain": map[string]any{
			"affinity":       map[string]any{"cold": 1.2, "wet": 0.9},
			"family":         "storm",
			"freezing":       true,
			"humidity_mod":   22.0,
			"name":           "冻雨",
			"precip_mm":      8.0,
			"pressure_delta": -10.0,
			"temp_delta":     -2.0,
			"visibility_mod": -12.0,
			"wind_mod":       1.5,
		},
		"gale": map[string]any{
			"affinity":       map[string]any{"wind": 2.0},
			"family":         "wind",
			"humidity_mod":   -5.0,
			"name":           "大风",
			"precip_mm":      0.0,
			"pressure_delta": -4.0,
			"temp_delta":     -1.0,
			"visibility_mod": -6.0,
			"wind_mod":       12.0,
		},
		"hail": map[string]any{
			"affinity":       map[string]any{"cold": 0.4, "wet": 1.0},
			"family":         "storm",
			"humidity_mod":   20.0,
			"name":           "冰雹",
			"precip_mm":      15.0,
			"pressure_delta": -14.0,
			"temp_delta":     -3.0,
			"visibility_mod": -16.0,
			"wind_mod":       6.0,
		},
		"haze": map[string]any{
			"affinity":       map[string]any{"cloud": 0.5, "dry": 0.4},
			"family":         "haze",
			"humidity_mod":   10.0,
			"name":           "霾",
			"precip_mm":      0.0,
			"pressure_delta": 2.0,
			"temp_delta":     0.0,
			"visibility_mod": -28.0,
			"wind_mod":       -2.5,
		},
		"heat": map[string]any{
			"affinity":       map[string]any{"dry": 0.7, "hot": 2.0},
			"family":         "heat",
			"hot_gate":       true,
			"humidity_mod":   -5.0,
			"name":           "高温",
			"precip_mm":      0.0,
			"pressure_delta": 2.0,
			"temp_delta":     8.0,
			"visibility_mod": 2.0,
			"wind_mod":       -0.5,
		},
		"heavy_rain": map[string]any{
			"affinity":       map[string]any{"wet": 1.5},
			"family":         "rain",
			"humidity_mod":   28.0,
			"name":           "大雨",
			"precip_mm":      30.0,
			"pressure_delta": -12.0,
			"temp_delta":     -3.0,
			"visibility_mod": -12.0,
			"wind_mod":       2.0,
		},
		"heavy_snow": map[string]any{
			"affinity":       map[string]any{"cold": 1.4, "wet": 1.0},
			"family":         "snow",
			"humidity_mod":   24.0,
			"name":           "大雪",
			"precip_mm":      18.0,
			"pressure_delta": -11.0,
			"snow":           true,
			"temp_delta":     -3.0,
			"visibility_mod": -14.0,
			"wind_mod":       2.0,
		},
		"light_rain": map[string]any{
			"affinity":       map[string]any{"wet": 1.0},
			"family":         "rain",
			"humidity_mod":   15.0,
			"name":           "小雨",
			"precip_mm":      3.0,
			"pressure_delta": -5.0,
			"temp_delta":     -1.0,
			"visibility_mod": -5.0,
			"wind_mod":       0.5,
		},
		"light_snow": map[string]any{
			"affinity":       map[string]any{"cold": 1.0, "wet": 0.6},
			"family":         "snow",
			"humidity_mod":   12.0,
			"name":           "小雪",
			"precip_mm":      2.0,
			"pressure_delta": -4.0,
			"snow":           true,
			"temp_delta":     -1.0,
			"visibility_mod": -4.0,
			"wind_mod":       0.5,
		},
		"moderate_rain": map[string]any{
			"affinity":       map[string]any{"wet": 1.3},
			"family":         "rain",
			"humidity_mod":   22.0,
			"name":           "中雨",
			"precip_mm":      12.0,
			"pressure_delta": -8.0,
			"temp_delta":     -2.0,
			"visibility_mod": -8.0,
			"wind_mod":       1.0,
		},
		"moderate_snow": map[string]any{
			"affinity":       map[string]any{"cold": 1.2, "wet": 0.8},
			"family":         "snow",
			"humidity_mod":   18.0,
			"name":           "中雪",
			"precip_mm":      8.0,
			"pressure_delta": -7.0,
			"snow":           true,
			"temp_delta":     -2.0,
			"visibility_mod": -8.0,
			"wind_mod":       1.0,
		},
		"overcast": map[string]any{
			"affinity":       map[string]any{"cloud": 1.0, "wet": 0.3},
			"family":         "cloud",
			"humidity_mod":   8.0,
			"name":           "阴",
			"precip_mm":      0.0,
			"pressure_delta": -3.0,
			"temp_delta":     -1.0,
			"visibility_mod": -3.0,
			"wind_mod":       0.0,
		},
		"partly_cloudy": map[string]any{
			"affinity":       map[string]any{"cloud": 0.6, "dry": 0.4},
			"family":         "cloud",
			"humidity_mod":   -5.0,
			"name":           "多云",
			"precip_mm":      0.0,
			"pressure_delta": 3.0,
			"temp_delta":     1.0,
			"visibility_mod": 8.0,
			"wind_mod":       0.0,
		},
		"rainstorm": map[string]any{
			"affinity":       map[string]any{"wet": 1.8},
			"family":         "storm",
			"humidity_mod":   33.0,
			"name":           "暴雨",
			"precip_mm":      70.0,
			"pressure_delta": -18.0,
			"temp_delta":     -4.0,
			"visibility_mod": -18.0,
			"wind_mod":       4.0,
		},
		"snowstorm": map[string]any{
			"affinity":       map[string]any{"cold": 1.5, "wet": 1.1, "wind": 0.6},
			"family":         "storm",
			"humidity_mod":   30.0,
			"name":           "暴雪",
			"precip_mm":      35.0,
			"pressure_delta": -16.0,
			"snow":           true,
			"temp_delta":     -4.0,
			"visibility_mod": -22.0,
			"wind_mod":       6.0,
		},
		"thunderstorm": map[string]any{
			"affinity":       map[string]any{"hot": 0.5, "wet": 1.4},
			"family":         "storm",
			"humidity_mod":   25.0,
			"name":           "雷阵雨",
			"precip_mm":      25.0,
			"pressure_delta": -15.0,
			"temp_delta":     -1.0,
			"visibility_mod": -14.0,
			"wind_mod":       5.0,
		},
	}
	BaselineWeatherStateOrder []any = []any{"clear", "partly_cloudy", "overcast", "light_rain", "moderate_rain", "heavy_rain", "rainstorm", "thunderstorm", "hail", "freezing_rain", "light_snow", "moderate_snow", "heavy_snow", "snowstorm", "fog", "haze", "dust", "heat", "cold_wave", "gale"}
)
